spring.application.name=RoomRentalManagementSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=270307
#spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

spring.cache.type=none

server.servlet.context-path=/api
server.port=8080

jwt.secret = 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
jwt.expiration = 259200000
jwt.refreshExpiration = 604800000

fe.host = http://localhost:2001/success
maijet.from = bachbom27@gmail.com



logging.file.name=D:/spring_log_file-api.log
logging.logback.rollingpolicy.max-file-size= 100KB
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


spring.mail.host=in-v3.mailjet.com
spring.mail.port=587
spring.mail.username=6b54cf4a1018e771fe5a0a58e3cd732d
spring.mail.password=8a8b97af1ab71d0d6c29dff3db53fbd1
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
